### ISSUE TITLE
Error while trying to launch the tile editor 

### ISSUE THREAD

**Issue by dderevjanik** [huguesjohnson/eisfrei#1]
Hi, I'm always getting this error:

```
Could not find file 'C:\Users\danie\Downloads\Herzog Zwei\data\Palette-Addresses.xdata'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at com.huguesjohnson.eisfrei.EisfreiUtils.deserialize(XmlSerializer serializer, String fileName)
   at com.huguesjohnson.eisfrei.MainForm.buttonLaunchTileEditor_Click(Object sender, EventArgs e)
```

![hz-error](https://cloud.githubusercontent.com/assets/4524497/25625247/57e665f6-2f5c-11e7-90ba-01f0c4904aa7.png)

I tried it with different roms, but result is same > every time I click on launch editor or on `palettes` tab, an error occurs.

**Comment by huguesjohnson** [comment]
Should be fixed now - https://github.com/huguesjohnson/eisfrei/commit/df127664f2d1f09ca8924a512be6cb29dfe9ade0
